# Site settings
title: 叨叨
email: wellber.wan@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: vincentkof
github_username:  vinwan
facebook_username:  wellber.wan

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]